default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "chat_system_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "chat_system_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "chat_system_production") %>
